### ISSUE TITLE
Delete user

### ISSUE THREAD

**Issue by danielalvsaaker** [danielalvsaaker/tf-viewer#12]
Implement the ability to delete a user and all owned activities.

**Comment by joaovitoriasilva** [comment]
Hello,

If someone wanted to have this tool published to the Internet for friends and family, the possibility to self register can be a problem. There should be an admin portal or something so the owner (singular or plural) can do identity management.

Thanks.

**Comment by danielalvsaaker** [comment]
That will happen in the next release. The plan is to run a separate user management/authentication system with an admin interface.
