### ISSUE TITLE
Feature requests?

### ISSUE THREAD

**Issue by datvance** [danielalvsaaker/tf-viewer#16]
I see other issues for upcoming features. Would you like new issues for other feature requests? I'm not expecting anything, but wondering how you are planning to develop the project. Off the top of my head...

- Config option for using miles instead of km
- Config option for changing date / time display
- Ability to disable registration
- Ability to add notes to activities

I've never used Rust, but if I can learn it, and you're open to PRs for any of these, I'll try my best.

**Comment by danielalvsaaker** [comment]
New issues for feature requests are fine, just be reasonable about the scale of a feature. Config options for example can go in a single issue. PR's are of course welcome! Assign yourself to an issue so no one does any unecessary work.

Let's keep this issue open until a simple contribution guideline is written.
