### ISSUE TITLE
Config options

### ISSUE THREAD

**Issue by danielalvsaaker** [danielalvsaaker/tf-viewer#17]
List over config options to be added:
-  [x] Ability to disable registration
-  [x] Metric/imperial units
-  [ ] Custom date format

Comment if you have a suggestion.

**Comment by vidarandrebo** [comment]
A possibility to edit the table columns that show up on the activity page. For example disable the calorie column.
Add a column for the bike used on the acitvity.

**Comment by danielalvsaaker** [comment]
This will no longer be config options, but passed as an argument in the url.
