### ISSUE TITLE
Docker container for Raspberry Pi?

### ISSUE THREAD

**Issue by conrad82** [danielalvsaaker/tf-viewer#25]
In the [readme](https://github.com/danielalvsaaker/tf-viewer#tf-viewer), it is mentioned that it runs on Raspberry Pi 3A+

The docker container on docker hub only supports linux/amd64, are there plans to build it also for ARM devices like the Pi?

**Comment by danielalvsaaker** [comment]
Yes, thanks for reminding me that I have to figure out how to cross-compile docker images.😁. I'll try to push out an ARM image this weekend.

**Comment by danielalvsaaker** [comment]
Cross-compiling turned out to be a bigger beast than I expected, but I finally made it work. Pull the newest docker image and let me know if it works!

**Comment by conrad82** [comment]
Thanks! :+1: 

It did not run, however :\

```
$ sudo docker pull danielalvsaaker/tf-viewer
Using default tag: latest
latest: Pulling from danielalvsaaker/tf-viewer
069a56d6d07f: Already exists 
08fbe2677d62: Pull complete 
fd4100ec53c5: Pull complete 
56a705699989: Pull complete 
Digest: sha256:3a03f64b011cfbf921dbf0b8039daffe0751d8c445db75d6ba760f4a9e3ffb42
Status: Downloaded newer image for danielalvsaaker/tf-viewer:latest
docker.io/danielalvsaaker/tf-viewer:latest


$ sudo docker run -e TZ='Europe/Oslo' -v data:/data -p 8081:8080 danielalvsaaker/tf-viewer
thread 'main' panicked at 'Failed to load: SledError { source: Unsupported("the \'compression\' feature must be enabled") }', src/main.rs:23:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Panic in Arbiter thread.

```

**Comment by danielalvsaaker** [comment]
Ok, I know why. Let me just rebuild and push.

**Comment by danielalvsaaker** [comment]
Pushed to docker hub.

**Comment by conrad82** [comment]
It works! Thanks! :) :1st_place_medal: 
Web page shows up

```
$ sudo docker run -e TZ='Europe/Oslo' -v data:/data -p 8081:8080 danielalvsaaker/tf-viewer
Config file not found, starting with defaults.
Cookie key is missing or shorter than 32 bytes, generating a key...
Running at 0.0.0.0:8080
```

https://github.com/danielalvsaaker/tf-viewer/commit/dcfdb99c5c40e5be8b8f1687458c64b3b3778baa https://github.com/danielalvsaaker/tf-viewer/commit/75f924422c632826dee988fb9da782575d6a034b https://github.com/danielalvsaaker/tf-viewer/commit/d8ddfaa27ae72a91659c2da6cd3d587614eec799
