### ISSUE TITLE
Activity gear

### ISSUE THREAD

**Issue by joaovitoriasilva** [danielalvsaaker/tf-viewer#27]
Hello,

Is it possible to implement an option to if selected the addition of the gear to a certain activity does not count to the "Total distance" field of the gear?

Thanks.

**Comment by danielalvsaaker** [comment]
This is a very specific request, and clunky to implement. Unless this is a feature that many can benefit from, I would recommend to just create a new gear entry with a similar name, and assign that gear to the specific activities in mind.

**Comment by danielalvsaaker** [comment]
Too specific, won't implement.
