### ISSUE TITLE
Recent activities UI issue

### ISSUE THREAD

**Issue by joaovitoriasilva** [danielalvsaaker/tf-viewer#28]
UI broken on "Recent activities" page.
![Broken](https://user-images.githubusercontent.com/8648976/113165974-4054f480-923a-11eb-8a01-616d66bf654a.PNG)

**Comment by danielalvsaaker** [comment]
Does the container have access to port 80/443 outgoing? It's necessary for retrieving map tiles.

**Comment by joaovitoriasilva** [comment]
Yes! The container has internet access.

**Comment by danielalvsaaker** [comment]
I think I've figured out the issue, but it will take some work. I will prioritize this when I have the time (probably in a month, unfortunately).

**Comment by danielalvsaaker** [comment]
The whole stack is being rewritten, with separate frontend and backend. Closing this, as this will not be fixed until rewrite is done.
