### ISSUE TITLE
Build from source when building Dockerfile

### ISSUE THREAD

**Issue by 13hannes11** [danielalvsaaker/tf-viewer#31]
I think for ease of use sake, it would be great to have the option to build from source when running the docker file. This would allow to build on systems that do not have rust installed and would be a first step towards making it possible to build via GitHub actions.

I'd suggest using a multi stage image for that. Moreover, we can copy the whole repository into the container therefore if a version exists that has been built outside of the container we can use this to speed up built time.

I'd be willing to work on that if you think this is a good idea.

**Comment by 13hannes11** [comment]
I just realised that it seems to already built from source, however I am unsure how to actually buld the docker-file, maybe something could be added to the readme.

**Comment by danielalvsaaker** [comment]
Hey!
There is an example command in the docker directory in this repository. The build file is a bit complicated, and I'll appreciate some help with setting up multi-stage build or simplifying the build file!
